root_dir: artifact

data_ingestion:
  root_dir: artifact/data_ingestion
  source_url: "https://github.com/HimmatMagar/datae/raw/refs/heads/main/personality_dataset.zip"
  zip_file: artifact/data_ingestion/data.zip
  unzip_file: artifact/data_ingestion

data_validation:
  root_dir: artifact/data_validation
  file_path: artifact/data_ingestion/personality_dataset.csv
  status_file: artifact/data_validation/status.txt


data_transformation:
  root_dir: artifact/data_transformation
  file_path: artifact/data_ingestion/personality_dataset.csv


model_building:
  root_dir: artifact/model_building
  x_train_file: artifact/data_transformation/x_train.pkl
  y_train_file: artifact/data_transformation/y_train.pkl
  model: model.pkl